Reproducible Research: Peer Assessment 1
========================================================

## Loading and preprocessing the data

```{r, results='hide'}
##Download and unzip the file
if(!file.exists("./data")){dir.create("./data")}
file<- "https://d396qusza40orc.cloudfront.net/repdata%2Fdata%2Factivity.zip"
download.file(file,destfile="./data/Data.zip", method='curl')

unzip(zipfile="./data/Data.zip",exdir="./data")

rm(file)

##New path
path <- file.path("./data")

##Open file
data <- read.csv(file.path(path,"activity.csv"), colClasses = c("integer", "Date", "factor"), header=T)
data$month <- as.numeric(format(data$date, "%m"))


##Complete data
c_data<-na.omit(data)
```

## What is mean total number of steps taken per day?
```{r}
library(ggplot2)
t_steps<-tapply(c_data$steps, c_data$date, sum, na.rm=T)
qplot(t_steps, binwidth = 1000, xlab = "total number of steps taken each day")

mean(t_steps, na.rm = TRUE)
median(t_steps, na.rm = TRUE)

```

## What is the average daily activity pattern?

```{r}
avg <- aggregate(c_data$steps, list(interval = as.numeric(as.character(c_data$interval))), FUN = "mean")
names(avg)[2] <- "mean"

ggplot(avg, aes(interval, mean)) + geom_line(color = "steelblue", size = 0.8) + labs(title = "Time Series Plot of the 5-minute Interval", x = "5-minute intervals", y = "Average Number of Steps Taken")
```

## Imputing missing values

```{r}
library(Hmisc)
library(ggplot2)

describe(data)
nrow(data[is.na(data$steps)==T,])

data<-merge(data,avg,all.x=T)
data$imp_steps<-ifelse(is.na(data$steps)==T,data$mean,data$steps)

t_steps2 <- tapply(data$imp_steps, data$date, FUN = sum)
qplot(t_steps2, binwidth = 1000, xlab = "Total number of steps taken each day")

```

## Are there differences in activity patterns between weekdays and weekends?

```{r}
data$days_type <- factor(format(data$date, "%A"))
data$days_type2<-ifelse(data$days_type=="sábado" | data$days_type=="domingo", "weekend","weekday")

avg2 <- aggregate(data$imp_steps,list(as.numeric(data$interval),data$days_type2), mean)
names(avg2) <- c("interval","day_type","mean")
avg2<-avg2[order(avg2[,1]),]
rownames(avg2)<-1:nrow(avg2)

library(lattice)
xyplot(avg2$mean ~ avg2$interval | avg2$day_type, 
       layout = c(1, 2), type = "l", 
       xlab = "Interval", ylab = "Number of steps")
```

